### ISSUE TITLE
Getting DNA fasta sequences of ORFs from a "fasta" file?

### ISSUE THREAD

**Issue by loukesio** [Roleren/ORFik#103]
Dear Roleren,

Thank you for your package. Its quite cool. Its not an issue but mostly a question. 
If I have fasta file and and want to export the ORF sequences out of it how could I do it with ORFik?
Here is an example, from here how can I export the ORF sequences. Its a simple fasta file of linear viral DNA

e.g., library(Biostrings)
Phi10<-readDNAStringSet("Phi_10_S7_40.87788.fna")
pos <- findORFs(Phi10, startCodon = "ATG", minimumLength = 0)
neg <- findORFs(reverseComplement(Phi10),
                startCodon = "ATG", minimumLength = 0)
pos <- GRanges(pos, strand = "+")
neg <- GRanges(neg, strand = "-")
res <- c(pos, neg)
res <- split(res, seq.int(1, length(pos) + length(neg)))

and then?

**Comment by Roleren** [comment]
Now you just extract fasta and save that. See the overview vignette of ORFik bioconductor page, to see how to do that. Let me know if something is unclear. :)

**Comment by loukesio** [comment]
Thanks Roleren, 
I am not sure which command I need to you for that. I checked the vignete but I am a bit off. 
If you could guide me in the exact command I would appreciate

**Comment by Roleren** [comment]
To get sequences do: orf_seqs <- extractTranscriptSeqs(Phi10, res)

To save do:
writeXStringSet(orf_seqs, filepath = "orfs.fasta")

Let me know if something does not work

**Comment by loukesio** [comment]
Yes, I have tried this in the first place and I am getting this error "Error in extractTranscriptSeqs(Phi10, res) : 
  the transcripts in 'transcripts' are on chromosomes that are not in 'x'"
Any idea why?

**Comment by Roleren** [comment]
Can you do: unique(seqnames(Phi10))
unique(seqnames(orf_seqs))

Do they chromosome names Match?

To check if one does not match do:
which(!(unique(seqnames(Phi10)) %in%
unique(seqnames(orf_seqs))))

**Comment by loukesio** [comment]
I can not do none of this because I am getting an error. I could send you file to have a look if you want (link here: https://1drv.ms/u/s!ArOzUuixE-mgwjlq09UBJdulZFut?e=sJ8lMq). From what I understand so far is that it finds ORFs in genomics ranges that are out of the width (or length) of my sequence.

**Comment by Roleren** [comment]
Change "orf_seqs" with "res", in the test I sent in last post, it should work and give you what does not match. I won't be on a computer for a few days, so send me the error if this still does not work.

**Comment by loukesio** [comment]
Sure thank you. I ll not send you :)

**Comment by Roleren** [comment]
Making an easy solution for you now, will let you know tomorrow

**Comment by Roleren** [comment]
I see this is hard to do actually, I never access ORFs from a simple list like this (I always use some genome annotation), but I will make a function for this, so you can do this in a single call, will add it to next release of ORFik.

For now do:

```
library(ORFik)
library(Biostrings)
library(GenomicFeatures)
faFile <- "~/Downloads/Phi_10_S7_40.87788.fna"
Phi10<-readDNAStringSet(faFile)
# Find ORFs and split
pos <- findORFs(Phi10, startCodon = "ATG", minimumLength = 0)
pos <- split(unlist(pos, use.names = FALSE), paste0("orf_pluss_", seq(length(unlist(pos)))))
neg <- findORFs(reverseComplement(Phi10),
                startCodon = "ATG", minimumLength = 0)
neg <- split(unlist(neg, use.names = FALSE), paste0("orf_minus_", seq(length(unlist(neg)))))
# Extract, must use unlisted object, that is why you got the error
orf_seqs_pos <- extractTranscriptSeqs(x = Phi10[[1]], transcripts = pos)
orf_seqs_pos
# Extract minus on reverse complement
orf_seqs_neg <- extractTranscriptSeqs(x = reverseComplement(Phi10)[[1]], transcripts = neg)
orf_seqs_neg 
# Save to file
writeXStringSet(c(orf_seqs_pos, orf_seqs_neg), "~/Desktop/orfs.fasta")
```

**Comment by loukesio** [comment]
Thank you Roleren I am gonna have a look at it first thing next morning. I appreciate your effort to understand and use ORFik
