### ISSUE TITLE
asTX not in namespace

### ISSUE THREAD

**Issue by hsinyenwu** [Roleren/ORFik#104]
Hi Roleren,

I am trying to use the asTX function in the ORFik package, but it seems that this function is not exported.

```r
asTX(grl,reference)
Error in asTX(grl,reference) :    could not find function "asTX"
```
or

```r
ORFik::asTX(grl,reference)
Error: 'asTX' is not an exported object from 'namespace:ORFik'
```

Is there an easy way to fix this?

Best,
Larry

**Comment by Roleren** [comment]
To access asTX directly, do: 
```r
# 3 colons
ORFik:::asTX
```

But it is just a wrapper to the important function which is pmapToTranscriptF, the only difference is that asTX fixes the problem of matching transcripts for you so that grl[1] is same tx as reference[1]. Does this answer your question ?

**Comment by hsinyenwu** [comment]
Hi Roleren, This is awesome. Thanks so much for your help!
