### ISSUE TITLE
findORFsFasta gives wrong start and stop codon

### ISSUE THREAD

**Issue by MaxLev** [Roleren/ORFik#105]
I posted on the Bioconductor forum but maybe it's simpler to directly report the issue on GitHub.

I am trying to extract ORFs from the human mitochondrial genome (circular genome). I am not familiar with the package so I started by running the following example which worked as expected.
```
require(BSgenome.Hsapiens.UCSC.hg38)
require(ORFik)

# Load example fasta file
example_genome <- system.file("extdata", "genome.fasta", package = "ORFik")

# Find ORFs
orfs <- findORFsFasta(example_genome, 
                      startCodon = "ATG", 
                      stopCodon = stopDefinition(2),
                      is.circular = TRUE)

# Get ORF sequences
genome <- readDNAStringSet(example_genome, format = "fasta")
names(genome) <- "Chromosome"
BSgenome::getSeq(genome, orfs[2])
```
DNAStringSet object of length 1:
    width seq 585 ATGATTGAAAAAACCATTAGCGGCCAGGATGCTTTACCCAATATC...ACGGGGTCTATACCTGCGACCCGCGTCAGGTGCCCGATGCGAGG

The result is an appropriate ORF. It starts with an ATG codon and ends by an AGG codon which is a termination codon in the vertebrate mitochondrial code as specified by the stopDefinition command.

However, the same approach fails when using a different fasta file, in this case a fasta of the complete human mitochondrial genome. The resulting ORFs do not have the right start and/or stop codons. This can be verified with the following commands:

```
# Get human mitochondrial genome
mtDNA <- DNAStringSet(BSgenome.Hsapiens.UCSC.hg38$chrM)
names(mtDNA) <- "chrM"
Biostrings::writeXStringSet(mtDNA, "mitochondrial_genome.fasta")

# Find ORFs from local copy of mitochondrial genome saved as fasta file
mtDNA_orfs <- findORFsFasta("mitochondrial_genome.fasta", 
                            startCodon = "ATG", 
                            stopCodon = stopDefinition(2),
                            is.circular = TRUE)

# Get ORF sequences from the mitochondrial genome
BSgenome::getSeq(mtDNA, mtDNA_orfs[3])
```
In this second example, the sequence extracted does not start with a start codon and terminates with a codon that isn't a vertebrate mitochondrial termination codon.

I don't know whether this is an actual issue or whether I am not using the function properly but any help would be greatly appreciated. 

Thanks!
Max

**Comment by Roleren** [comment]
Hey, will check this now and come back to you in a few hours.

**Comment by Roleren** [comment]
Confirmed, there is a bug when using this genome, here is a test to verify:

```
library(ORFik); library(Biostrings)
require(BSgenome.Hsapiens.UCSC.hg38)

# First test ORFik ranges
example_genome <- system.file("extdata", "genome.fasta", package = "ORFik")
a <- findORFsFasta(example_genome,
                   startCodon = "ATG",
                   stopCodon = stopDefinition(2),
                   is.circular = F)
a <- a[strandBool(a)]
genome <- readDNAStringSet(example_genome)
b <- findORFs(genome, startCodon = "ATG", stopCodon = stopDefinition(2))
# a and b should output identical ORFs
identical(ranges(a), ranges(unlist(b, use.names = FALSE)))

# Now test on hg38 data

mtDNA <- DNAStringSet(BSgenome.Hsapiens.UCSC.hg38$chrM)
names(mtDNA) <- "chrM"
Biostrings::writeXStringSet(mtDNA, "~/Desktop/mitochondrial_genome.fasta")

# a and b should output identical ORFs
a <- findORFsFasta("~/Desktop/mitochondrial_genome.fasta",
                                                startCodon = "ATG",
                                                stopCodon = stopDefinition(2),
                                                is.circular = F)
a <- a[strandBool(a)] # Only + strand ORFs

b <- findORFs(mtDNA, startCodon = "ATG", stopCodon = stopDefinition(2))
identical(ranges(a), ranges(unlist(b, use.names = FALSE)))
# For hg38 there is a bug!
```

**Comment by Roleren** [comment]
So, I should have done this a long time ago, I have changed to use the biostrings C API for reading fasta files, there was some unusual formatting of the fasta file that biostrings catches while ORFik did not, it now works, try this:

```r
library(ORFik); library(Biostrings)
require(BSgenome.Hsapiens.UCSC.hg38)

mtDNA <- DNAStringSet(BSgenome.Hsapiens.UCSC.hg38$chrM)
names(mtDNA) <- "chrM"
# a and b should output identical ORFs
a <- findORFsFasta(mtDNA,
                   startCodon = "ATG",
                   stopCodon = stopDefinition(2),
                   is.circular = F)
a <- a[strandBool(a)] # Only + strand ORFs

b <- findORFs(mtDNA, startCodon = "ATG", stopCodon = stopDefinition(2))
identical(ranges(a), ranges(unlist(b, use.names = FALSE)))
```

**Comment by Roleren** [comment]
pushed to Bioconductor devel and release, should be there in 3 days if you dont want to use github devel version

**Comment by MaxLev** [comment]
Thank you for fixing the issue so quickly! That works perfectly now!
