### ISSUE TITLE
Have no function 'bedToGR'

### ISSUE THREAD

**Issue by MuradOmarov** [Roleren/ORFik#113]
Hi!
Thanks for your great tool! 
I'm trying to use ORFik to analyze uORFs. And I want to find them in regions between start sites of assembled transcripts and annotated CDS start sites. 
So I want to add this regions from Bed-file 
`b =read.table('UTRs.bed')`
`bedToGR(b)
`
Error in bedToGR(b) : could not find function "bedToGR"

My console output during installation:

Bioconductor version 3.14 (BiocManager 1.30.15), R 4.1.0 (2021-05-18)
Installing package(s) 'ORFik'
trying URL 'http://bioconductor.org/packages/3.14/bioc/bin/macosx/contrib/4.1/ORFik_1.13.2.tgz'
Content type 'application/x-gzip' length 4250572 bytes (4.1 MB)
==================================================
downloaded 4.1 MB

tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/_k/nmqkfdns21752hfl4205tzgw0000gp/T//RtmpKEqFge/downloaded_packages
Warning message:
In .inet_warning(msg) :
  unable to access index for repository http://bioconductor.org/packages/3.14/data/annotation/bin/macosx/contrib/4.1:
  cannot open URL 'http://bioconductor.org/packages/3.14/data/annotation/bin/macosx/contrib/4.1/PACKAGES'

Thanks in advance!

**Comment by Roleren** [comment]
hehe, yeah, this function is only for internal use, and is not exported (AKA, another function is what you should use): 

if you try:

```
library(ORFik)
fread.bed('UTRs.bed') # This uses fread, so much faster than read.table
```

I even have a function that loads any file type:

`fimport('UTRs.bed')` # Works for bed, bam, wig, ofst, ++

You should not use internal functions. But if you wanted to, you would have to do:

b <- read.table('UTRs.bed')
ORFik:::bedToGR(b) # To access internal functions use 3 :::

Let me know if you have more questions.

**Comment by MuradOmarov** [comment]
Got you! Thanks! It works
