### ISSUE TITLE
How to get count tables for Genes rather than trancript?

### ISSUE THREAD

**Issue by QianzhaoJ** [Roleren/ORFik#115]
Hi,
Thanks for developing such helpful tool !
I want to get count tables for GeneID rather than each trancript, like HTSeq command `htseq-count -f bam -i gene_id -t CDS`, and the output as follows:

```
ENSG00000000003	528
ENSG00000000005	0
ENSG00000000419	644
ENSG00000000457	143
ENSG00000000460	337
ENSG00000000938	0
ENSG00000000971	964
ENSG00000001036	2531
ENSG00000001084	166
ENSG00000001167	255
```
Each row has one gene, and these genes are not duplicated.

When using ORFik, I ran `countTable_regions(df.rfp,regions="cds",lib.type = "pshifted", rel.dir = "pshifted")` and got
all transcript isoforms per gene. And when I changed some options, and ran `countTable_regions(df.rfp,longestPerGene=T,geneOrTxNames="gene",regions="cds",lib.type = "pshifted", rel.dir = "pshifted")`, I got same output as before. There are all transcript isoforms per gene.

So How to get count tables for Genes rather than trancript? Could you give me some suggestions?

Bests,
Qianzhao

**Comment by Roleren** [comment]
So I advice you always to store the list with all isoforms, with txNames, and when you actually want with longest isoform per gene, do this:

First make count table with all isoforms with txNames:
`countTable_regions(df.rfp,regions="cds",lib.type = "pshifted", rel.dir = "pshifted")`

Then load and subset to unique isoforms:
```
table <- countTable(df.rfp, "cds", type = "summarized")
table <- table[filterTranscripts(df.rfp, 0, 1, 0, longestPerGene = T)] # Convert to unique per gene (by longest)
names(table) <- ORFik::txNamesToGeneNames(names(table), df.rfp) # If you want them with gene names
```

I made your first attempt not work as a safety so people did not make tables that would not work together, I could implement if you like have the countTable function have longestPerGene = TRUE / FALSE if you want ?

Then you could just do:
`table <- countTable(df.rfp, "cds", type = "summarized", longestPerGene = T, by = "genes")`

**Comment by Roleren** [comment]
Even though I do not advice it, since a lot of bad things can happen. Like loading 1 count tables with gene unique isoforms (For ribo-seq) and 1 with all isoforms with txNames (for RNA-seq), I now allow what you wanted originally:
`countTable_regions(df.rfp,longestPerGene=T,geneOrTxNames="gene",regions="cds",lib.type = "pshifted", rel.dir = "pshifted")`

Will now work, install by doing:

devtools::install_github("Roleren/ORFik")

But remember if you load RNA-seq from original countTable, they will not be by gene. 
Also remember if you want to remake a table, do forceRemake = TRUE (only in newest version), this remake the table, instead of loading the already made one.

Let me know if you have any more questions :)

**Comment by Roleren** [comment]
Did it work for you ?
Did you have any more questions

**Comment by QianzhaoJ** [comment]
Hi,
Thanks for your help ! I have used another way to get count tables for each gene as follows `featureCounts -t CDS -g gene_id -O -s 1`. 
I am going to try ORFik for counting reads, but I confused about the difference between ORFik  and featureCounts. If I want to get same count table as `featureCounts` using ORFik, how should I set the parameters in ORFik?

Thanks again!
Best,
Qianzhao

**Comment by Roleren** [comment]
The above call to featureCounts does this:
Get all CDS, by unique isoform (the gene definition), then count all reads in strand specific manner (-s argument).

To do this in ORFik, first install newest version:
`devtools::install_github("Roleren/ORFik")`

Then do: 
`table <- countTable(df.rfp, "cds", type = "summarized", longestPerGene = T, by = "genes")`

If there are any differences left it means the featureCounts does not choose the longest CDS isoform as default, but rather the largest genomic coordinates isoform. But these differences should be very small if at all.

Let me know how it works and if you are missing something.

**Comment by Roleren** [comment]
Will close issue in 2 days if there is nothing else :)
