### ISSUE TITLE
`findUORFs` fails on hg38 with `Error in .check_exon_chrom(tx1)`

### ISSUE THREAD

**Issue by edikedik** [Roleren/ORFik#117]
Hi,

I'm trying to utilize the function `findUORFs` on hg38 assembly to find the coordinates of all possible uORFs possibly spanning into CDSs. Hence, I'm doing the following:
```R
library("ORFik")
library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("BSgenome.Hsapiens.UCSC.hg38")

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
bsgm <- BSgenome.Hsapiens.UCSC.hg38::Hsapiens
fiveUTRs <- loadRegion(txdb, "leaders")
cds <- loadRegion(txdb, "cds")

uORFS <- findUORFs(fiveUTRs, bsgm, "ATG", cds = cds)
```

This fails with an error
```
Error in .check_exon_chrom(tx1) (ORFik_sandbox.Rmd#42): Some transcripts (e.g. ENST00000399012.6, ENST00000430923.7, etc...) have exons located on more than
  one chromosome. This is not supported yet.
```

Alternatively, I tried another approach using `findMapORFs`:
```R
tx_seqs <- extractTranscriptSeqs(bsgm, fiveUTRs)
fiveUTR_ORFs <- findMapORFs(
  fiveUTRs, tx_seqs,
  startCodon = "ATG")
```
This does not raise an error unless I'm trying to extract the sequences of `fiveUTR_ORFs` using
```R
fiveUTR_ORFs_seqs <- extractTranscriptSeqs(bsgm, fiveUTR_ORFs)
```
which causes the same error as above.

I realize that it's likely a problem with the `GenomicFeatures` package, not `ORFik`, but, still, I hope you could give me some hints to bypass this problem.

**Comment by Roleren** [comment]
Hey, will test it. Can you run and send me your info about R settings:
sessionInfo()

**Comment by Roleren** [comment]
ok, figured it out:

This genome is malformed, contains some bad errors I believe. The gene I describe below is from X/Y homology region, and should only be described by one of x or y, here they use both for some reason. I always use Ensembl official genomes, which you can get with:

`annotation <- ORFik::getGenomeAndAnnotation("Homo sapiens", file.path(ORFik::config()["ref"], paste0("Homo_sapiens_GRCh38_", db)), optimize = TRUE)`
This genome will be optimized by ORFik to load much faster than the one you have, but will of course take some time to download and set up. So skip it if you are not going to work a lot on this thing.

But to make this genome annotation work, note some genes are on multiple chromosomes:
```
cds[names(cds) %in% "ENST00000244174.10"]
GRangesList object of length 2:
$ENST00000244174.10
GRanges object with 9 ranges and 3 metadata columns:
      seqnames              ranges strand |    cds_id    cds_name exon_rank
         <Rle>           <IRanges>  <Rle> | <integer> <character> <integer>
  [1]     chrX 155997760-155997787      + |    272219        <NA>         1
  [2]     chrX 156002906-156003019      + |    272222        <NA>         2
  [3]     chrX 156003449-156003560      + |    272223        <NA>         3
  -------
  seqinfo: 640 sequences (1 circular) from hg38 genome

$ENST00000244174.10
GRanges object with 9 ranges and 3 metadata columns:
      seqnames            ranges strand |    cds_id    cds_name exon_rank
         <Rle>         <IRanges>  <Rle> | <integer> <character> <integer>
  [1]     chrY 57184280-57184307      + |    277109        <NA>         1
  [2]     chrY 57189426-57189539      + |    277112        <NA>         2
  [3]     chrY 57189969-57190080      + |    277113        <NA>         3
  -------
  seqinfo: 640 sequences (1 circular) from hg38 genome
```
In my Ensembl genome, this is only on X, which is what it should be.
So to make it work, we simply remove the "false" duplicates.

```
length(cds) # <- duplicates 
length(cds[!duplicated(names(cds))]) # <- This is the one we want
cds <- cds[!duplicated(names(cds))]
fiveUTRs <- fiveUTRs[!duplicated(names(fiveUTRs))]
uORFS <- findUORFs(fiveUTRs, bsgm, "ATG", cds = cds)

```

**Comment by edikedik** [comment]
Works now.

For the records:
1. Downloaded the annotation
```R
anno <- ORFik::getGenomeAndAnnotation(
  "Homo sapiens",
  file.path(conf["ref"], paste0("Homo_sapiens_GRCh38_", "ensembl")),
  optimize = TRUE)
```
2. Using the downloaded files, initialized `txdb` and `fasta` files:
```R
fa <- FaFile(file.path("path/to/.fa"))
txdb <- loadTxdb("path/to/.db")
```
3. `uORFS` is populated as expected. 
```R
fiveUTRs <- loadRegion(txdb, "leaders")
cds <- loadRegion(txdb, "cds")
uORFS <- findUORFs(fiveUTRs, fa, "ATG", cds = cds)
```

Thanks for your help!
