### ISSUE TITLE
Handling nested uORFs

### ISSUE THREAD

**Issue by joegage** [Roleren/ORFik#119]
I see some discussion in #57 over how ORFik handles nested uORFs when `longestORF=TRUE`, but I want to clarify what happens when `longestORF=FALSE`.

I am doing some work that involves searching not only for uORFs that already exist in the sequence, but also potential uORFs that could be mutated to uORFs with a single base pair change in the stop codon. I'm doing this by passing all codons that are 1bp mutation away from TAA|TAG|TGA, which is quite a few potential stops. When I do this though, even with `longestORF=FALSE`, I am getting a fairly short list of uORFs - fewer than when I run with the default stop codons. I expect that I should see an immense number of uORFs with my long list of 1-bp-away-from-TAA|TAG|TGA codons, but that is not the case.

In additon, the uORFs that are being reported with my long list of stop codons tend to be shorter than when I run with the standard set of stop codons. Does ORFik scan backwards from each potential stop codon looking for all in-frame starts? Or is there some other constraint that is causing it to terminate the search early?

Thanks!

**Comment by Roleren** [comment]
Hey, will take a look, and see if the problem is out end. 
To make the search as fast as possible it is done by in C++ with a Knuth-Morris-Prat like string search combined with a binary search for start/stop links. So step 1. Find all start and stops, step 2. Binary search for first downstream stop still available per start. 
If longestORF is true, only return longest per stop codon. 

This should work even with your non canonical stops. 
Will let you know if I find something.

**Comment by joegage** [comment]
Okay, I think this explains what I am seeing then. If both TCG and TAG are passed as possible stop codons, then a sequence like ATG-NNN-TCG-TAG would only return ATG-NNN-TCG, and not also ATG-NNN-TCG-TAG? That seems like reasonable behavior for finding uORFs in most circumstances - my "1-SNP-distance" criterion is just not quite suited to the same manner of search.

**Comment by Roleren** [comment]
Let me know if you found a solution, if there is more need for this in the community I could think about implementing it.

Else I will close this issue in a week :)

**Comment by joegage** [comment]
I ended up using UTRAnnotator (https://github.com/ImperialCardioGenetics/UTRannotator) which I think is more suited for evaluating the effects of polymorphisms on uORFs. I still use ORFik for identifying uORFs in genomic sequence, but I think that my initial use case was not quite appropriate for what the software was designed to do!
