### ISSUE TITLE
computeFeatures() doesn't not work with GAlignmentPairs

### ISSUE THREAD

**Issue by matanel-y** [Roleren/ORFik#126]
Hello,

I have paired-end RNA-seq data and single-end RFPs. I used ORFikQC() to create the .ofst files.

I am trying to use computeFeatures() as in the Ribo-Seq tutorial vignette with my data

> dt_ctl1 <- computeFeatures(cds,
>                       RFP = fimport(filepath(df.rfp[5,], "pshifted")),
>                       RNA = fimport(filepath(df.rna[5,], "ofst")), Gtf = df.rfp,
>                       grl.is.sorted = TRUE, faFile = df.rfp,
>                       weight.RFP = "score", weight.RNA = "score", uorfFeatures = FALSE)

> Error in checkRNA(class(RNA)) : RNA must be either GAlignments or GRanges

Class check:

>RNA = fimport(filepath(df.rna[5,], "ofst"))
>class(RNA)

>[1] "GAlignmentPairs"
>attr(,"package")
>[1] "GenomicAlignments"

If I try to change class:

>class(RNA) = "GAlignments"
>Error in start(x) : 
  >no slot of name "start" for this object of class "GAlignments"

Any help would be appreciated! Thank you!

**Comment by Roleren** [comment]
ops, yes, that one is easy to fix, as paired end reads should be accepted, I just made the filter there a bit too strict, 
will let you know when I push a fix

**Comment by Roleren** [comment]
pushed, let me know if there is anything wrong downstream, else I will close the issue tomorrow

**Comment by matanel-y** [comment]
Works great! Thank you!
