### ISSUE TITLE
FindORFsFasta frame!

### ISSUE THREAD

**Issue by Fedeluppi** [Roleren/ORFik#127]
Hi Roleren :)

Thank you for creating this package, it is really useful and very fast :)

I have a question concerning the function `findORFsFasta`. Is there a way to know the frame of transcription? The function reports information on the strand and the genome coordinates but there is no way (at least I have not found one!) to output the frame as well. It would be also useful to know what do you consider as frame. Do you just starting to read the genome from the second nucleotide or do you consider the second appearance of a starting codon as another frame?

```This is my code:
# select bacterial genetic code
bact = getGeneticCode(id_or_name2="Bacterial, Archaeal and Plant Plastid",full.search = T)
# find ORFs specifying possible start and stop codons and minimum sequence length
orfs = findORFsFasta("/Users/luppino/ownCloud/GitLab/denovo_proteins/seq.fasta",longestORF = F,startCodon = startDefinition()[9],stopCodon = stopDefinition()[1],is.circular = T,minimumLength = 48)
# source the ecoli genome fasta file
fa   = FaFile("/Users/luppino/ownCloud/GitLab/denovo_proteins/seq.fasta")
# create names for ORFs found
names(orfs) = paste0("ORF_", seq.int(length(orfs)),"_ecoli","_",ranges(orfs),"_",strand(orfs))
# map ORFs to genomic sequence
orf_seqs    = getSeq(fa, orfs)
# translate ORFs into amino acids sequence
orf_seqs    = Biostrings::translate(orf_seqs, genetic.code = bact, no.init.codon = T)
names(orf_seqs) = names(orfs)
```

**Comment by Roleren** [comment]
Internally in c code the frame is stored (defined as position of first nt in ORF modulus 3, the position is relative to input sequence (genomic or tx coordinates). So in R just recreate it with this: 

```
frame = (start(orf)-1) %% 3  ## frame 0 means same frame as start of input sequence
```

This is the default definition of frame and is used extensively internally in ORFik.

**Comment by Fedeluppi** [comment]
Thank you for your prompt and exhaustive reply!
