### ISSUE TITLE
STAR.index for small genomes

### ISSUE THREAD

**Issue by yeroslaviz** [Roleren/ORFik#130]
in order for STAR to work correctly with smaller genomes, it  is recommended to change the ` --genomeSAindexNbases` parameter while indexing.

Is this possible from within the package and this command, or do I need to give it a script?

If needed I can also modify the internal Orfik script, but I don't think it is a good idea.

thanks

**Comment by Roleren** [comment]
Ignore this warning unless it crashes, the modern version of star usually handles this very well. Did it actually crash or just give a warning?

**Comment by yeroslaviz** [comment]
No, the indexing went well, and this was a warning only.

but it crashes during the mapping with the following error

```
EXITING because of FATAL input ERROR: --limitIObufferSize requires 2 numbers since 2.7.9a.
SOLUTION: specify 2 numbers in --limitIObufferSize : size of input and output buffers in bytes.
```

I'm using STAR 2.7.10a

In order to overcome this, I have modified the  lines in the script `RNA_Align_pipeline.sh` script to be as such:

`--limitIObufferSize 30000000 50000000`

I'm testing it now.

**Comment by yeroslaviz** [comment]
Just wanted to say, that changing the `--limitIObufferSize` parameter fixed this issue.

**Comment by Roleren** [comment]
Yes, so here is a small problem in a sense, because ORFik supports STAR 2.7.4a. So this is more a request for enhancement, will see if I have the time to add it in. If not for you, just use the  RNA_Align_pipeline.sh each time. Your hassle now is that you need to remember to use it each time, while with 2.7.4a it just works :)

**Comment by yeroslaviz** [comment]
Not sure if it will continue working, but for simplicity, I have put the modified file in the same STAR_Aligner folder and it seems to work fine for now. let's see how it goes.
