### ISSUE TITLE
shiftFootprintsByExperiment in the vignette does not work

### ISSUE THREAD

**Issue by yeroslaviz** [Roleren/ORFik#131]
When following the vignette of the data management part, running the command `shiftFootprintsByExperiment` produces an error:

```
shiftFootprintsByExperiment(df[df$libtype == "RFP",])
```

```
Error: BiocParallel errors
4 remote errors, element index: 1, 2, 3, 4
0 unevaluated and other errors
first remote error:
Error in detectRibosomeShifts(rfp, txdb = loadTxdb(df), start = start, : Library contained no periodic or accepted read-lengths, check your library. Are you using the correct genome? Is this Ribo-seq?
```

any ideas?

**Comment by yeroslaviz** [comment]
When following the vignette of the data management part, running the command `shiftFootprintsByExperiment` produces an error:


```
shiftFootprintsByExperiment(df[df$libtype == "RFP",])
```

```
Error: BiocParallel errors
4 remote errors, element index: 1, 2, 3, 4
0 unevaluated and other errors
first remote error:
Error in detectRibosomeShifts(rfp, txdb = loadTxdb(df), start = start, : Library contained no periodic or accepted read-lengths, check your library. Are you using the correct genome? Is this Ribo-seq?
```

any odeas?

**Comment by yeroslaviz** [comment]
> Tested on my end, it works here. If you shift the files 1 by 1 the other way does it work ?
> 
> Try this: what is your output?
> 
> detectRibosomeShifts(fimport(filepath(df[1,], type = "ofst")), txdb = loadTxdb(df))


Tried again, with a new environment and still got the same error.

When running the command you mentioned, I get this error:

```
> detectRibosomeShifts(fimport(filepath(df[1,], type = "ofst")), txdb = loadTxdb(df))
Notification: All widths are 1, using score column for widths, remove score column and run again if this is wrong.
Error in detectRibosomeShifts(fimport(filepath(df[1, ], type = "ofst")),  : 
  No valid read lengths found with accepted.lengths and counts > min_reads
```

the error repeats when I run it only for one file

```
> shiftFootprintsByExperiment(df[9,])
Shifting reads in experiment: ORFik_example_human
Saving ofst files to: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/ORFik/extdata/Homo_sapiens_sample/pshifted/
Saving wig files to: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/ORFik/extdata/Homo_sapiens_sample/pshifted/
/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/ORFik/extdata/Homo_sapiens_sample/ofst/RFP_Mutant_rep1.ofst
Notification: All widths are 1, using score column for widths, remove score column and run again if this is wrong.

Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in detectRibosomeShifts(rfp, txdb = loadTxdb(df), start = start, : Library contained no periodic or accepted read-lengths, check your library. Are you using the correct genome? Is this Ribo-seq?
```

What `txdb` should one use for it to run?

I am also  attaching the commands I have tried to re-run, which produces this errors.


[snippet.R.txt](https://github.com/Roleren/ORFik/files/10661508/snippet.R.txt)


thanks for the help

Assa

**Comment by Roleren** [comment]
Hm.. Something is wrong with your ofst file I think:

For me if I do this:
`fimport(filepath(df.rfp[1,], type = "ofst"))`

I get this:
GAlignments object with 245507 alignments and 1 metadata column:
             seqnames strand       cigar    qwidth     start       end     width     njunc |     score
                <Rle>  <Rle> <character> <integer> <integer> <integer> <integer> <integer> | <integer>
       [1]          1      -         49M        49     17610     17658        49         0 |         1
       [2]          1      -         27M        27     17718     17744        27         0 |         1

What do you get ?

**Comment by yeroslaviz** [comment]
I am not sure, what might be wrong, as I don't change them. I am getting a `GRanges` object. 

```
fimport(filepath(df[1,], type = "ofst"))
GRanges object with 102 ranges and 2 metadata columns:
        seqnames    ranges strand |     score      size
           <Rle> <IRanges>  <Rle> | <numeric> <numeric>
    [1]     chr1       306      + |        25         1
    [2]     chr1       308      + |         3         1
    [3]     chr1       309      + |         8         1
    [4]     chr1       310      + |         2         1
    [5]     chr1       313      + |         1         1
    ...      ...       ...    ... .       ...       ...
```

(I don't have the df.rfp object, but I guess we mean the same here.)

Just to make sure, I have downloaded the ORFiK library from Bioc to check and rerun the same command with the ofst files from there. It is the same.

```
fimport(path = "~/Downloads/ORFik/inst/extdata/Homo_sapiens_sample/RFP_Mutant_rep1.ofst")
GRanges object with 2946 ranges and 2 metadata columns:
         seqnames    ranges strand |     score      size
            <Rle> <IRanges>  <Rle> | <numeric> <integer>
     [1]     chr1       306      + |         2        29
     [2]     chr1       307      + |         2        29
     [3]     chr1       308      + |         7        28
     [4]     chr1       310      + |        10        29
     [5]     chr1       311      + |        10        27
     ...      ...       ...    ... .       ...       ...
 ```

How can I get the `GAlignments` object from that?

thanks

Assa

**Comment by Roleren** [comment]
Still bugged ?

**Comment by Roleren** [comment]
Will close in a few days if no more help is needed :)

**Comment by yeroslaviz** [comment]
Hi Håkon,

thanks for the great help and I'm sorry i haven't tested it yet. 

Thanks to the talk with Michal and his really useful explanations about my problem I have solved my problem(s) using RiboCrypt. 

I'm still planning on testing/trying your newly made pakcage on creating the data from scratch using massiveNGSpipe and follow this with the ORFiK analysis. 

I will do it and if encounter any more problems. I'll contact you again.

Is ORFiK already compatible with Bioconductor 3.17?

thanks

For now this can be closed.

Assa
