### ISSUE TITLE
 download.SRA.metadata gets only 11 samples (supposedly shuld be 12)

### ISSUE THREAD

**Issue by yeroslaviz** [Roleren/ORFik#137]
when following the vignette for RiBo-Seq, I encounter a couple of difficulties. (If preferable , I can split them over two different issues).

1.   download.SRA.metadata problem
When downloading the metadata (and the fastq files) using  `download.SRA.metadata` or  `download.SRA` functions only five RNA-Seq samples are being downloaded. the sample RNA-Seq CO2 is not being downloaded. I can't explain why. I have needed to download this sample manually and add it to the raw data folder manually. 

The error pop up only when trying to create the experiment with triplicate for each sample, but only two exists for the `CO` samples.

2. HeatMapRegion error

running this command throws an error (seemingly with BiocParallel, even though it doesn't make sense), but I can't explain why this is happening as well:

```
> heatMapRegion(df.rfp, region = c("TIS", "TTS"), shifting = "5prime", type = "ofst", outdir = file.path(QCfolder(df.rfp), "heatmaps/pre-pshift/"))
Plot save location:
/fs/home/yeroslaviz/Bio_data/processed_data/Ribo-seq/Alexaki_Human/aligned/QC_STATS//heatmaps/pre-pshift/
TIS
Outputting libraries from: Alexaki_Human_Ribo-seq
1 :  RFP_CO_r1

2 :  RFP_CO_r2

3 :  RFP_CO_r3

4 :  RFP_WT_r1

5 :  RFP_WT_r2

6 :  RFP_WT_r3

[1] "RFP_CO_r1 5prime transcriptNormalized"
Error: BiocParallel errors
  1 remote errors, element index: 1
  5 unevaluated and other errors
  first remote error:
Error in coverage$score: object of type 'closure' is not subsettable
In addition: There were 16 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In coverage_to_dt(coverage, keep.names = keep.names, withFrames = withFrames,  ... :
  No coverage found, Returning empty data.table!
2: In coverage_to_dt(coverage, keep.names = keep.names, withFrames = withFrames,  ... :
  No coverage found, Returning empty data.table!
3: In coverage_to_dt(coverage, keep.names = keep.names, withFrames = withFrames,  ... :
  No coverage found, Returning empty data.table!
```
(all 16 warnings are identical).

thanks

Assa

**Comment by Roleren** [comment]
1. Your ORFik version is old, this does not happen to me: do devtools::install_github("Roleren/ORFik")

2. Something is wrong with you coverage. restart R and remove all objects and try again, if it still fails run: debug(ORFik:::heatMap_single), I think that is where the error happens. Then run again heatMapRegion. It should start debug at correct break point.

Let me know if it does not work :)

**Comment by Roleren** [comment]
Also for 2:
To replicate error do this:

min(GenomicRanges::coverage$score)

It somehow thought coverage is a function and not a data.table which it is. 
The error happens in ORFik:::coverageHeatMap

**Comment by Roleren** [comment]
This should be solved in newest ORFik, let me know if it is still not.
Else I close this issue in 2 days.
