### ISSUE TITLE
`computeFeatures` throws error when trying to compute sequence features (bacterial genome)

### ISSUE THREAD

**Issue by m-jahn** [Roleren/ORFik#138]
Hi!
Thanks for making this very versatile package.
I'm currently doing an analysis of bacterial ribosome footprinting data. I followed the steps in the different vignettes and everything mostly worked fine. Now I ran `computeFeatures` on P-shifted RPF data (with optional RNAseq input) and if I set `sequenceFeatures = TRUE` I  get an error. I strongly suspect that the error is caused by non-standard bacterial genome annotation. I can see in the traceback that the function is looking for 5' UTR info but the genome annotation does not have these features. Some more details about my code and input data follows.

Running this throws error:
```
computeFeatures(
  grl = list_tx,
  RFP = bam_riboseq_shifted[[1]],
  RNA = bam_rna[[1]],
  Gtf = txdb,
  faFile = fasta_ref_genome,
  uorfFeatures = TRUE,
  sequenceFeatures = TRUE
)
```
Presence of RNAseq data does not play a role, neither does the fasta file that is supplied. The txdb is a standard NCBI Refseq genome annotation for  a bacterium imported from a `gff`file. `list_tx` is a record of transcripts, extracted from this genome annotation like this:

```
txdb <- ORFik::loadTxdb("./genome/GCF_000006785.2/genomic.gff")
list_tx <- ORFik::loadRegion(txdb, "tx")
```

I have found no possibility to manipulate the txdb file in R. I suspect that adding 5'UTR info could fix this bug. The genome annotation can be downloaded from NCBI, e.g. here: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000006785.2/

Most importantly, this is the error message I got:

```
Error: subscript contains invalid names
24.
stop(wmsg(...), call. = FALSE)
23.
.subscript_error("subscript contains invalid ", what)
22.
NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
allow.NAs = allow.NAs)
21.
NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
allow.NAs = allow.NAs)
20.
normalizeSingleBracketSubscript(i, x, as.NSBS = TRUE)
19.
METHOD(x, i)
18.
extractROWS(x, i)
17.
extractROWS(x, i)
16.
subset_along_ROWS(x, i, drop = drop)
15.
.nextMethod(x = x, i = i)
14.
eval(call, callEnv)
13.
eval(call, callEnv)
12.
callNextMethod(x = x, i = i)
11.
fiveUTRs[txNames(ORFs)]
10.
fiveUTRs[txNames(ORFs)]
9.
validGRL(class(grl))
8.
widthPerGroup(fiveUTRs[txNames(ORFs)], FALSE)
7.
distToCds(grl, fiveUTRs, cds)
6.
eval(jsub, SDenv, parent.frame())
5.
eval(jsub, SDenv, parent.frame())
4.
`[.data.table`(scores, , `:=`(distORFCDS, distToCds(grl, fiveUTRs, 
cds)))
3.
scores[, `:=`(distORFCDS, distToCds(grl, fiveUTRs, cds))]
2.
allFeaturesHelper(grl, RFP, RNA, tx, fiveUTRs, cds, threeUTRs, 
faFile, riboStart, riboStop, sequenceFeatures, uorfFeatures, 
grl.is.sorted, weight.RFP, weight.RNA)
1.
computeFeatures(grl = list_tx, RFP = bam_riboseq_shifted[[1]], 
RNA = bam_rna[[1]], Gtf = txdb, faFile = fasta_ref_genome, 
uorfFeatures = TRUE, sequenceFeatures = TRUE)
```

Thanks a lot,
Michael

**Comment by m-jahn** [comment]
Thanks for your quick feedback! I will try that and get back with more info.

**Comment by m-jahn** [comment]
I tested some things that you suggested, unfortunately I stumbled upon some more errors but maybe some of them can be fixed.
I tried to make the txdb file with using `makeTxdbFromGenome`. That gives an error on the genome gtf file I linked previously. (note that it was not modified by me in any way but plainly taken from NCBI). The error I got is from this line:

`percentage <- round((length(leaders) / length(cds))*100, 1)`

The result with a genome that has no leader sequences is `NaN` and the following if clause (`if (percentage < 30) { ... }`) fails when it tries to evaluate that.
I cloned the ORFik package and fixed the bug like this, see this git diff. Here it tests if there are any leaders at all and if not, skips the calculation.

```
-      percentage <- round((length(leaders) / length(cds))*100, 1)
       message("- Total leaders: ", length(leaders))
-      message("- Leader length statistics:")
-      print(summary(widthPerGroup(leaders, FALSE)))
+      if (length(leaders) > 0) {
+        percentage <- round((length(leaders) / length(cds))*100, 1)
+        message("- Leader length statistics:")
+        print(summary(widthPerGroup(leaders, FALSE)))
+      }
+      else {
+        percentage <- 0
+        message("- Leader length statistics:")
+      }
```
The second error is less trivial because it seems to lie with `GenomicFeatures`. The error I get is from the function attempting to map CDSs to exons. But bacterial genomes have not really exons, nor do they splice, so here we would need a parameter that skips these operations. Any ideas? I think these BioC packages should be general enough to also work with non-eukaryotic genomes. Here's the error:

```
Error in .make_splicings(exons, cds, stop_codons) : 
some CDS cannot be mapped to an exon
5.
stop(wmsg("some CDS cannot be mapped to an exon"))
4.
.make_splicings(exons, cds, stop_codons)
3.
makeTxDbFromGRanges(gr, metadata = metadata)
2.
GenomicFeatures::makeTxDbFromGFF(gtf, organism = organismCapital, 
chrominfo = fa.seqinfo) at txdbHelpers.R#61
1.
makeTxdbFromGenome(gtf, genome, organism, optimize = TRUE, pseudo_5UTRS_if_needed = 100, 
return = TRUE)
```

Thanks for your help!

**Comment by Roleren** [comment]
You are indeed right, the ORFik error I could not replicate, but you fixed that anyway.

For me it crashes in GenomicFeatures and from debugging I see they have something missing in their code here:

GenomicFeatures::makeTxDbFromGRanges

From line 29 in the function:

```
noextx_IDX <- .get_noextx_IDX(tx_IDX, mcols0$ID, exon_IDX, 
    mcols0$Parent)
  if (length(noextx_IDX) != 0L) {
    cds_with_noextx_parent_IDX <- .get_cds_with_noextx_parent_IDX(cds_IDX, 
      mcols0$Parent, noextx_IDX, mcols0$ID)
    exon_IDX <- sort(c(exon_IDX, cds_with_noextx_parent_IDX))
  } 
```
This part is suppose to add in the exon ids missing (which are only in CDS).

While it does not happen, because .get_noextx_IDX, does not actually compare to cds exons given.
Exons have 82, while CDS has 1769 in your case.

Could you make an issue in genomic features and reference this point. 

If you could also propose a fix and justify it, they will much more quickly add it in.

This is all very strange, as someone should have caught this before now..

**Comment by Roleren** [comment]
I got this assembly to work, see if it works for you?
https://bacteria.ensembl.org/Streptococcus_pyogenes_stab902_gca_000732425/Info/Index

had to add a small fix in ORFik, so do
devtools::install_github("Roleren/ORFik") first.

**Comment by m-jahn** [comment]
Thanks! I will try and get back.

**Comment by m-jahn** [comment]
With the new ORFik version and the genome from ensemble it actually works, thanks!
It should nevertheless also work with data from NCBI Genomes. I will file an issue with `GenomicFeatures`.
One more question, when running `ORFik::makeTxdbFromGenome(...)` the execution of the function stops in the middle and waits for user input, caused by the `browser()` statement. Is this intentional? I just skipped it with `c` and then the function runs til the end without error.

**Comment by Roleren** [comment]
Ah, yes, that is not supposed to be there :D
Pushing fixed version without browser.

**Comment by m-jahn** [comment]
Very interesting, is this a Shiny app?
BTW I will close this now as the error lies not with your package
