### ISSUE TITLE
Problem with detectRibosomeShifts in a non-reference species

### ISSUE THREAD

**Issue by JC-therea** [Roleren/ORFik#141]
Hello again,

Im having a problem with the function `detectRibosomeShifts()`. It is super useful however there is a function inside (`seqlevelsStyle()`) forcing it to have a genome style and, for my species, there is no option to select. More in detail the error is the following

```
Error in seqlevelsStyle(seqlevels) : 
  The style does not have a compatible entry for the species supported by Seqname. Please see genomeStyles() for
  supported species/style
```

Is there any option to deactivate that part of the function?

Thank you again for your quick responses

**Comment by Roleren** [comment]
So keepSeqlevels is the thing that actually fails?

If you are unsure do:

`debug(detectRibosomeShifts)`

Then run as before, press 'enter' to move downwards with debug mode, line by line, if you want to step inside a function, press 's' then enter

**Comment by JC-therea** [comment]
I was testing and the line was 
```
footprints <- fimport(footprints, cds)
```

**Comment by Roleren** [comment]
K, will make a fix and let you know :)

**Comment by Roleren** [comment]
Ah, wait I thought I fixed this, maybe it is not on Bioconductor yet:

Try github devel, do: 
`devtools::install_github("Roleren/ORFik")`
Then restart R, press session tab on top of RStudio and click Restart R.

Then try again

**Comment by Roleren** [comment]
Did it work ?

**Comment by JC-therea** [comment]
Sorry for the delay. We are having a net problem and I was not able to test it. As soon as I try it I will let you know!

**Comment by Roleren** [comment]
Most likely tomorrow, i did this months ago, but somehow it is not there yet
