### ISSUE TITLE
Wrong antisense ORF

### ISSUE THREAD

**Issue by johannesnicolaus** [Roleren/ORFik#143]
I tried to use the function findMapORFs, but it seems like I keep on getting wrong result on the antisense strand. I can't seem to pinpoint the problem because it seems to work on the example in the vignette

The following are the input data:

The coordinates:
```
GRangesList object of length 1:
$g1.t1
GRanges object with 7 ranges and 6 metadata columns:
      seqnames        ranges strand |   source              type     score     phase transcript_id     gene_id
         <Rle>     <IRanges>  <Rle> | <factor>          <factor> <numeric> <integer>   <character> <character>
  [1]     chr1 149856-149874      - | AUGUSTUS exon                   0.58      <NA>         g1.t1          g1
  [2]     chr1 149136-149170      - | AUGUSTUS exon                   0.93      <NA>         g1.t1          g1
  [3]     chr1 148999-149092      - | AUGUSTUS exon                   0.99      <NA>         g1.t1          g1
  [4]     chr1 148783-148942      - | AUGUSTUS exon                   1.00      <NA>         g1.t1          g1
  [5]     chr1 148595-148736      - | AUGUSTUS exon                     NA      <NA>         g1.t1          g1
  [6]     chr1 149875-149894      - | AUGUSTUS 5_prime_extension      0.58      <NA>         g1.t1          g1
  [7]     chr1 148545-148594      - | AUGUSTUS 3_prime_extension        NA         1         g1.t1          g1
  -------
  seqinfo: 19 sequences from an unspecified genome; no seqlengths
```

The sequence:
```
AACAAGTCAATTGAATAAACGGTTTTGAATTGAATTGCCATTTTATTCAACAAAACCAGCAAATGGCTTGACGACGAAGAAATAGACTTTAAGAAAAATCTGTACACGCGCGCTTGGTGTTCAAAATCAGAACAGCTTAAAAAAGACAGTAAAGCTGAGGAAGAAATAAAATTACAATATCTTTTGCCTTAAATCATGCTGAGTGGAAAAATCTCAATATTGAACACAATTCCGTAATACTAAGCGACAACACTCTTCTTGAATCTGCTTTTTCAACGCTAAAAGCCAGACAGCGAGTCGATACAAAGAGTTTAAATATCAATATTTATCGATCGGCAGCTCTCAAAATAAGGCGATATACAAAGCAGCTTCGAAAGAAGAGAAAAAGTACATGAATGATGAAATTCACGAAAACGCATCTGAGATTCTTAAAAAGCTATTCAAAGAAGACGACACTAAACAAAGCGTTCCAAATCTTGAGATGTCAACGTGCTTCCTAGCTAGAATGCGTCTCAGAACA
```

The command:
```r
ORFs <- findMapORFs(grl = grl, 
            seqs = sequences,
            startCodon = "ATG") 
```

And the result
getSeq(genome, ORFs[1] %>% sort())

```
DNAStringSetList of length 1
[["g1.t1_1"]] g1.t1=TTGAACACAATTCCGTAATACTAAGCGACAACACTCTTCTTG
```

**Comment by johannesnicolaus** [comment]
Just to update, maybe it's easier to replicate the following:

given sequences A and B, where B is a subset of A with 1 exon as opposed to A that contains 2 exons

A:
```
ATCATGCTGAGTGGAAAAATCTCAATATTGAACACAATTCCGTAATACTAAGCGACAACACTCTTCTTGAATCTGCTTTTTCAACGCTAAAAGCCAGACAGCGAGTCGATACAAAGAGTTTAAATATCAATATTTATCGATCGGCAGCTCTCAAAATAAGGCGATATACAAAGCAGCTTCGAAAGAAGAGAAAAAGTACATGAATGATGAAATTCACGAAAACGCATCTGAGATTCTTAAAAAGCTATTCAAAG
```

B:
```
ATCATGCTGAGTGGAAAAATCTCAATATTGAACACAATTCCGTAATACTAAGCGACAACACTCTTCTTGAATCTGCTTTTTCAACGCTAAAAGCCAGACAGCGAGTCGATACAAAGAGTTTAAATATCAATATTTATCGATCGGCAGCTCTCAAAATAAG
```

A_exon
```
GRangesList object of length 1:
$test
GRanges object with 2 ranges and 6 metadata columns:
      seqnames        ranges strand |   source     type     score     phase transcript_id     gene_id
         <Rle>     <IRanges>  <Rle> | <factor> <factor> <numeric> <integer>   <character> <character>
  [1]     chr1 148783-148942      - | AUGUSTUS     exon      1.00      <NA>         g1.t1          g1
  [2]     chr1 148999-149092      - | AUGUSTUS     exon      0.99      <NA>         g1.t1          g1
  -------
  seqinfo: 19 sequences from an unspecified genome; no seqlengths
```

B_exon
```
GRangesList object of length 1:
$test
GRanges object with 1 range and 6 metadata columns:
      seqnames        ranges strand |   source     type     score     phase transcript_id     gene_id
         <Rle>     <IRanges>  <Rle> | <factor> <factor> <numeric> <integer>   <character> <character>
  [1]     chr1 148783-148942      - | AUGUSTUS     exon         1      <NA>         g1.t1          g1
  -------
  seqinfo: 19 sequences from an unspecified genome; no seqlengths
```

When I try to use `findMapORFs`, I get 2 different results:

A_ORFs
```
GRangesList object of length 1:
$test_1
GRanges object with 1 range and 1 metadata column:
       seqnames        ranges strand |       names
          <Rle>     <IRanges>  <Rle> | <character>
  test     chr1 149048-149089      - |      test_1
  -------
  seqinfo: 19 sequences from an unspecified genome; no seqlengths
```

B_ORFs
```
GRangesList object of length 1:
$test_1
GRanges object with 1 range and 1 metadata column:
       seqnames        ranges strand |       names
          <Rle>     <IRanges>  <Rle> | <character>
  test     chr1 148898-148939      - |      test_1
  -------
  seqinfo: 19 sequences from an unspecified genome; no seqlengths
```

The length seems to be the same, but the coordinate is incorrect for A. I'm not sure if I'm understanding something wrongly, so please let me know if I didn't understand the usage of the function correctly.

**Comment by Roleren** [comment]
Hm, yeah, looks like you are using a custom gtf or loading it in some strange way. When loading in normal way "-" strand is sorted in decreasing manner, while your transcripts are not. 

Try to call sortPerGroup, on input exons for findMapORFS, as for speed optimization I did not add a grl object verifier in that one. Then your minus exons are sorted decreasingly.

**Comment by Roleren** [comment]
I put sortPerGroup into a lot of the functions in ORFik since I knew this would happen, but have not done it for this one, will consider adding it in :)

**Comment by Roleren** [comment]
Anyway, generic rule is always sort if you load nonstandard files or make your own objects from scratch :)

**Comment by johannesnicolaus** [comment]
Hi @Roleren thank you very much!!! At first I also thought that this happened due to sorting problems and I tried sorting using the function `sort()` but seems like it didn't work for some reason. Seems like it's fixed by using `sortPerGroup`! Thanks a lot!!

**Comment by Roleren** [comment]
Yes, so inside ORFik, there is a module I call TranscriptRanges (like GRanges), so it does many of the low level utilities core Bioconductor packages are missing, like proper sorting of transcripts etc. 

Hard to know all the problems that occurs with exons groups, sorting is one of the biggest pitfalls for most people :)

**Comment by johannesnicolaus** [comment]
Thanks! I would probably suggest adding the sorting problem to the vignette, or incorporating the sorting function to the functions that doesn't have it yet. Feel free to close the issue if  you think it's not really an issue!

**Comment by Roleren** [comment]
To not break the package's logic, I will add the sort and set it to FALSE by default. This way the documentation will guide people to set this to TRUE If they are unsure if the ranges are sorted. 

For large amounts of Granges, there is a significant penalty for sorting, so I try to avoid this if not strictly necessary. 

Will close this issue, when this feature is pushed to github

**Comment by Roleren** [comment]
This is now supported, devtools::install_github("Roleren/ORFik") for working version.
