### ISSUE TITLE
Custom list of potential ORFs

### ISSUE THREAD

**Issue by colin986** [Roleren/ORFik#146]
Hello, 

I hope you’re well. 

I was wondering if it is possible to provide a custom list of ORFs to ORFik. The ORFs have been found by using harringtonine to identify the TIS and CHX for elongation and then ORF-Rater.

I’ve been trying to do this so by using FindMapOrfs and then overlapping with the coordinates of the custom list and subsetting the grl with the resulting matches. 

I’m hoping to use computeFeatures but this is failing when sequence features = T. Works Ok with sequence feature = F.  

Is there a better way to do this? Make a new grl for ORFs from a bed file and making sure the ORF is in the same format? 

Any advice would be appreciated!

Colin

**Comment by Roleren** [comment]
That is possible yes.

So bioconductor revoles around Genomic Ranges.

So you need to check 2 things:
1. Define GRangesList (either subset findMapORFs or create from your table), if subsetting make sure it is genomic coordinates  (for transcript coordinates, use ORFik::pmapFromTranscriptF() to get genomic, also make sure your are using the same assembly as your gene annotation. It sounds like your subsetting worked, and any subset of GRL should work with sequence features = T. So my guess is you mixed some seqinfo objects here (like different fasta genome vs gtf or something? (example would be chromosome 1 is called chr1 vs 1 etc) Could you send me the error ?
2. When this is done, you can run. Only way it can fail is if your seqinfo/seqlevels do not match, as I stated above.

Let me know how it goes.

**Comment by Roleren** [comment]
Did you resolve your problem? :)

**Comment by Roleren** [comment]
Will close the issue, reopen if you still have problems :)
