### ISSUE TITLE
question about fragment length

### ISSUE THREAD

**Issue by ynjin-neo** [Roleren/ORFik#147]
Hello

I just started trying ORFik recently but am just a wetlab biologist with a basic level of computational skills. I am still struggling to go through all the steps. 
As I have read instruction, I saw  "your trimmed reads should be no longer than 55 nt, else STAR (using the default local alignment) will not be able to find the 28nt of the read".  However, I am planning to do RCP-seq in which SSU contains fragments longer than 60nt, as your group published before. In that case, how can I analyze Riboseq for SSU or longer fragments? 

Thanks for your help!

**Comment by Roleren** [comment]
Cool, good luck with the protocol. Which species btw ?

So for SSU, this rule does not apply. What it means is that 50% of the read must map, for ribo this is 28*2, but for 60nt SSU this is 60*2, so it will be no problem for you. The bigger concern for you is to optimize the amount of SSU fragments you get, vs rRNA and lincRNA etc. This can be detected during ORFikQC step. We believe size fractionation and which RNAse used is the most important.

**Comment by ynjin-neo** [comment]
Hi there
Thanks for your advice!  Does that mean I can just use the same settings in STAR for SSU as shown in the introduction? Or are there more instruction about SSU?  So I actually didn't really finish going through all the step, so I could have missed some info written in your instruction.  
Btw, we are using zebrafish as shown in your Cell Rep paper. As for size fractionation and RNase digestion, we have spent quite some time to optimize it so I think that part is probably ok. But analysis part is our weakness at this moment.
Thansk again,

**Comment by Roleren** [comment]
Sorry for late answer, but the yes you can use the same STAR settings.

**Comment by Roleren** [comment]
Any more questions regarding that else I will close the issue :)
