### ISSUE TITLE
QC Error

### ISSUE THREAD

**Issue by hector3500** [Roleren/ORFik#148]
When I try to conduct the QC on my experiments the BAM files output fine, get converted to ofst files, and have read length tables created for them, though an error keeps popping up after this step: 

> ORFikQC(df.rfp)
Started ORFik QC report for experiment: Riboseq_1_Drosophila
Saving, ofst files to: /home/harrison/Documents/RiboSeq/Untrimmed_reads/Trimgalore_reads/PolA_trimmed/Mapped/Sorted/Unique_2/ofst/
Outputting libraries from: Riboseq_1_Drosophila
--------------------------
Converting libraries to new format: ofst
RFP_RPS3_r1
fstcore package v0.9.14
(OpenMP detected, using 8 threads)
RFP_RPS3_r2
RFP_RPS3_r3
RFP_RPS3.XRP1_r1
RFP_RPS3.XRP1_r2
RFP_RPS3.XRP1_r3
RFP_WT_r1
RFP_WT_r2
RFP_WT_r3
--------------------------
- Creating read length tables:
Outputting libraries from: Riboseq_1_Drosophila
Outputting libraries from: Riboseq_1_Drosophila
**Error: BiocParallel errors
  5 remote errors, element index: 1, 3, 5, 7, 9
  4 unevaluated and other errors
  first remote error:
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'seqlevelsStyle': cannot open the connection**

**Comment by Roleren** [comment]
Hey, the error: "cannot open the connection", means file paths are wrong most likely.

Can you send me the information of file paths you defined in your ORFik experiment, that is

`filepath(df, "default") # <- df is the ORFik experiment`

Also, could you try this:

```
rfp <- fimport(filepath(df, "default")[1]) # Load first bam file directly
seqlevelsStyle(rfp) # Check seqlevels Style can be read correctly
```

**Comment by hector3500** [comment]
Hey, I'll just give you the full experiment:

create.experiment(
 file.path("/home/harrison/Documents/RiboSeq/Untrimmed_reads/Trimgalore_reads/PolA_trimmed/Mapped/Sorted/Unique_2"),
  exper = "Riboseq_1_Drosophila",
  fa = "genome",
  txdb = "gtf",
  organism = 'Drosophila melanogaster',  
  viewTemplate = FALSE,
  pairedEndBam = FALSE,
  rep = c(1,2,3,1,2,3,1,2,3),
  condition = rep(c("RPS3", "RPS3.XRP1","WT"), each = 3),
  libtype = "auto",
  stage = "auto"
)

I already defined the genome and gtf paths previously.

**Comment by Roleren** [comment]
Yeah, so that wont do, I need to see the actual output, and this must also be wrong, as this will not work:
`txdb = "gtf"`

it should this I guess?:
`txdb = gtf`

**Comment by Roleren** [comment]
I think I need the specified outputs I required above to be able to know what is going on, as your definition above hides too many details

**Comment by hector3500** [comment]
okay so the genome and gtf paths are:
genome = "/home/harrison/Documents/RiboSeq/Genome/Drosophila_melanogaster.BDGP6.46.dna_sm.toplevel.fa"
gtf = "/home/harrison/Documents/RiboSeq/Genome/Drosophila_melanogaster.BDGP6.46.57.gtf" 

I removed the quotation marks, still the same error though. When you say outputs do you mean the paths for the output ofst and readLengths file? I didn't define output paths, it automatically places them in the file.path directory I initially specified.

**Comment by hector3500** [comment]
Here's the rest of the commands follwing the created experiments (I also have an RNAseq experiment): 

df.rfp <- read.experiment("Riboseq_1_Drosophila")
df.rna <- read.experiment("RNAseq_1_Drosophila")

ORFikQC(df.rfp)
ORFikQC(df.rna)

**Comment by Roleren** [comment]
Yes, and show me the console output when you run these lines:

```
filepath(df.rfp, "default") # <- df.rfp is the ORFik experiment
rfp <- fimport(filepath(df.rfp, "default")[1]) # Load first bam file directly
seqlevelsStyle(rfp) # Check seqlevels Style can be read correctly
```

**Comment by Roleren** [comment]
Any more questions? 
Else I will close the issue :)
