### ISSUE TITLE
Makar Issue - Incorrect Assignment of PMID

### ISSUE THREAD

**Issue by JackCurragh** [Roleren/ORFik#149]
The SRA Entrez API within ORFik incorrectly assigns studies with the PMID of 1 where no other valid PMID is found. This means a lot of studies end up being by Makar et al. when assigned via ORFik. 

I suspect [this](https://github.com/Roleren/ORFik/blob/edeb1d4d3dcc4a69ba197376ce2afb029051daa8/R/SRA_Entrez_API.R#L116C1-L117C1) line is to blame. 

Setting the default to 0 instead will not return a valid record from entrez but I am not sure how to test what impact this will have on the rest of the API.

**Comment by Roleren** [comment]
Thank, will check it out within a few and push if it works :)

**Comment by Roleren** [comment]
Ok, fixed, this was stupid, have no idea why I set it to default 1, 
I now set it to as.numeric(NA), and it works as it should, haha :D
