### ISSUE TITLE
version imcompatible between ORFik and biomartr

### ISSUE THREAD

**Issue by Shiywa** [Roleren/ORFik#152]
Hello,
         thanks for your job for ORFik. Recently, I found an error about version incompatible between `ORFik` and `biomartr`.

When I use `getGenomeAndAnnotation` to get genome from ensembl, I got an error information like: 
```
Error in biomartr:::getENSEMBL.gtf(organism = organism, type = "dna",  : 
  参数没有用(id.type = assembly_type)
```

 I found that `getGenomeAndAnnotation` get gtf files using `getENSEMBL.gtf`, but in the function:

```
 gtf <- get_genome_gtf(GTF, output.dir, organism, assembly_type, 
    db, gunzip, genome, optimize = optimize)
```

however, in the `biomartr v1.0.7`, the `getENSEMBL.gtf` has only four parameters like 

```
getENSEMBL.gtf(organism, type = "dna", path, release = NULL)
```

   maybe this function `getGenomeAndAnnotation` need to be improved.

sincerely !

**Comment by Shiywa** [comment]
Fine, now I'm in `R 4.2.0` and my `ORFik` is `1.16.6`.  I guess the error is due to the old version.

**Comment by Roleren** [comment]
Yes, so to explain the problem arises because CRAN and bioconductor are not synced in release windows. 

We recently updated biomartr, but that does not propagate to bioconductor packages like ORFik. 
So there is no way around this failing in your case.

Did the new version work ? :)

**Comment by Shiywa** [comment]
Sorry, it didn't work. now my `ORFik` is `1.23.5`. however, The function `getGenomeAndAnnotation` is similar to old version like :
```
    gtf <- get_genome_gtf(GTF, output.dir, organism, assembly_type, 
    db, gunzip, genome, optimize = optimize)
```
however, the error information is still like :
```
Error in biomartr:::getENSEMBL.gtf(organism = organism, type = "dna",  : 
  参数没有用(id.type = assembly_type)
```
my `biomartr` is `1.0.7`, is it too old ?

sincerely 
!

**Comment by Roleren** [comment]
Did you restart R now?

**Comment by Shiywa** [comment]
Thanks for your help. This step is done after update `ORFik` and restart R.
