### ISSUE TITLE
`computeFeatures` silently removes suffixes from gene names and crashes

### ISSUE THREAD

**Issue by m-jahn** [Roleren/ORFik#154]
Hi!
I ran into a bug (or a feature?) from `computeFeatures`. It took me a while to track it down because the error message was not informative. Basically, when I run the following non-reproducible example:

```
computeFeatures(
  grl = test_grl,
  RFP = bam_rfp,
  RNA = bam_rna,
  Gtf = txdb
)
```

I got the error:

```
Error: subscript contains invalid names
```

The example data is not really important because I found out that the error is caused by these lines in `allFeaturesHelper()`

```
# txNames() removes ORF suffixes e.g. the "_0001" in "SPV_0001"
tx <- tx[names(tx) %in% txNames(grl, tx, unique = TRUE)]

# then this line fails because "SPV" does not exist in the reference txdb
tx <- tx[txNames(grl)] # Subset tx to only those in grl.
```

If an ORF has a name with underscore like `SPV_0001`, the suffix gets silently removed and the function fails in the next line.
I would expect that there's at least a warning, or even better if there's a choice (a parameter) for not clipping suffixes in the `computeFeatures()` function.

**Comment by Roleren** [comment]
Yes, good idea, I'll add a suffix removal argument. This is a features because reference genomes have never used this naming, so it is shortest suffix for uorfs etc. But for custom genomes this can be an issue. Will let you know when it is pushed.

**Comment by Roleren** [comment]
Ok, I thought a bit about this and I think I have made a failsafe version. Since I originally thought people would use normal references here, I used the standard "_\\d" for uORFs to be a subset of transcripts, but this fails for custom gtfs.

Now txnames first checks the reference, to validate that it indeed does not use "_\\d" for normal transcript names.

Could you run this and test for your data:

```
devtools::install_github("Roleren/ORFik") # Now restart R after it is done, else new version is not loaded!
library(ORFik)
computeFeatures(
  grl = test_grl,
  RFP = bam_rfp,
  RNA = bam_rna,
  Gtf = txdb
)
```

Does it work now?

**Comment by m-jahn** [comment]
thanks! I will test ASAP.

**Comment by m-jahn** [comment]
Just tested it and it seems to work. I close the issue, thanks!
