### ISSUE TITLE
SRA Toolkit Binary and OS mismatch

### ISSUE THREAD

**Issue by SuhasSrinivasan** [Roleren/ORFik#161]
Hi,

This issue was observed on Ubuntu 22.04, when using the `download.SRA` function for the first time, the SRA toolkit which is downloaded does not match the Linux distribution.

`sratoolkit.2.10.9-centos_linux64` was downloaded instead of `sratoolkit.X.Y.Z-ubuntu64`.

Also, the auto SRA toolkit seems to be referring to an old binary.
The current binaries are at the below page without having to depend on URLs with version numbers.
https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit

**Comment by Roleren** [comment]
Centos binary runs fine on ubuntu I think, but I updated it to support ubuntu custom binary now. 
Also update to toolkit version 2.11.3 in newest master branch commit.
Reopen if there are any issues.
