### ISSUE TITLE
BiocFileCache path is not easy to use

### ISSUE THREAD

**Issue by SuhasSrinivasan** [Roleren/ORFik#168]
Hi,

Would it be possible to change the default directory of `BiocFileCache`?

It is currently in a hidden directory and nested, and the file names are randomly generated.

```
Setting up config file for ORFik
This config defines where to save:
            fastq, bam files, references and experiments
Saving to:  /home/user1/.cache/R/BiocFileCache/fa8a388fb8_fa8a388fb8.csv
ORFik now uses BiocFileCache for config, moving your old config
```

**Comment by Roleren** [comment]
Hi, this was required by bioc, who did not like how I had it. All the logic is the same, just hidden files. You can still open and edit files, and get the path to file from R. I will see if there is anything I can do about it :)

**Comment by Roleren** [comment]
If default is not sufficient, set it by:
BiocFileCache::setBFCOption("CACHE", "/I_want_it/here")
