### ISSUE TITLE
fastp number of threads is set to logical cores / 2

### ISSUE THREAD

**Issue by SuhasSrinivasan** [Roleren/ORFik#173]
Hello!

When using `STAR.align.folder(max.cpus = 28)` expected that **28** is passed to fastp too.
But actual command is `fastp --thread 16`

Will be helpful if `max.cpus` value is passed to fastp.

```
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS
ORFik_1.22.2
```

**Comment by Roleren** [comment]
FASTP has no gains after 16 cores, this I have tested, it actually makes it slower. This is why it is not set to anything more than 16. I will make a note in documentation of that :)
