### ISSUE TITLE
Out of Memory error shiftFootPrint function

### ISSUE THREAD

**Issue by josefinaperalba** [Roleren/ORFik#179]
Hi! I'm running the following code with some big bam files

```
bam_file <- fimport(
    opt$bam
)


offsets <- ORFik::detectRibosomeShifts(
    footprints = bam_file,
    txdb = opt$ref_db
    #minCDS = 20,
    #top_tx = 100
)

bam_file_shifted <- ORFik::shiftFootprints(
    footprints = bam_file,
    shifts = offsets
)

export.ofst(
    bam_file_shifted,
    file = opt$out_ofst
)

export.ofst(
    convertToOneBasedRanges(
        bam_file_shifted,
        addScoreColumn = TRUE,
        addSizeColumn = TRUE
    ),
    file = opt$out_ofst_ww
)
```

But I'me getting the following error **'R_Realloc' could not re-allocate memory (18446744065128005632 bytes)**. Is there a way to optimize this in a way it doen's consume this much memory? I'm running this in order to use the shifted files with the orfik features function.

Thank you so much!

**Comment by Roleren** [comment]
18446744065128005632 bytes = 18 446 744.1 terabytes (18 Million terabytes!)

What are you loading and at what step does this error happen ?

**Comment by Roleren** [comment]
First thing to try:
Dont load the bam file before you insert it into ORFik::detectRibosomeShifts:
so change to this:
```
bam_file <- fimport(
    opt$bam
)
bam_file <- opt$bam
```
Since R does not copy by reference, it will actually have 3 versions of the bam file in memory if you load it first, while only 1 if you give path.

**Comment by antoniasaracco** [comment]
okay, but in that case I need to load it before the shiftFootprints function right? Because that function doesn't allow a path as an input or is there a more memory efficient way to do it?

**Comment by Roleren** [comment]
True, I will update the function to support file path input, will do some tests on how much memory this saves :)

**Comment by Roleren** [comment]
10 is good for human default, depends on species, but don't touch it unless you have a good reason :)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Roleren** [comment]
BTW, could you do one thing first, I need to see if it fails here or not:

ORFik:::convert_bam_to_ofst(df)

Then run using the ofst files you get as output.
The point is that these are collapsed and compressed to fst, I always make collapsed ofst of the bam (BEFORE) I input into the detectRibosomeShifts function.

Since bam files is a very old format, it should only be loaded into R once, that is when calling convert_bam_to_ofst, after that only use bam to load custom flags (like multimapper flag etc).

Especially when you have a 39GB bam file, which is unusually large.

**Comment by antoniasaracco** [comment]
Hi! Thanks for all your repsonses! This strategy of converting to ofst before shifting worked for all the files smaller than 30GB so I'll just work with that limit. Thank you so much again!

**Comment by Roleren** [comment]
So to complete the biggest file you can do this trick (If the error is loading in the full 39GB bam):
I have not tested this code, just wrote it from my head, but should be almost correct:

```
# Goal: Read in 2 halfs, collapse duplicates, save 2 files, read in both, collapse the merge of these two and save out again.

df <- read.experiment()
big_bam_path <- filepath(df, "default)[index_of_bigest_file,]
ofst_basename <- paste0(ORFik:::remove.file_ext(big_bam_path, TRUE), ".ofst")
ofst_big_path <- file.path(dirname(big_bam_path), "ofst", ofst_basename)
ofst_big_path_temp <- tempfile()
load_half_bam <- collapseDuplicatedReads(readBam(big_bam_path, settings_to_read_half_file) # Read half file
                                    addScoreColumn = TRUE,
                                    addSizeColumn = TRUE)


export.ofst(load_half_bam, ofst_big_path_temp)
rm(load_half_bam) # remove first half
load_half_bam <- collapseDuplicatedReads(readBam(big_bam_path, settings_to_read_second_half_file) # Read half file
                                    addScoreColumn = TRUE,
                                    addSizeColumn = TRUE)
export.ofst(load_half_bam, ofst_big_path)
rm(load_half_bam) # remove second half

# Merge and export
# Sadly, ofst does not support appending files on drive, so we need to read in both halfs and save again
first_half <- fimport(ofst_big_path_temp)
second_half <- fimport(ofst_big_path)
combined <- collapseDuplicatedReads(sort(c(first_half, second_half)), 
                                    addScoreColumn = TRUE,
                                    addSizeColumn = TRUE)
export.ofst(load_half_bam, ofst_big_path) # Now you have the correct OFST
```

**Comment by antoniasaracco** [comment]
Hi! Sorry to bother but I saw that you commited an update where you fixed the bug in Shiftfootprints and I wanted to check if that already makes it possible for the function to accept a path as input. The reason I ask is because I've tried running it again with the path and the error I get comes from the ReadWidth function saying: _Error in readWidths(footprints, along.reference = TRUE) : reads must be either GRanges, GAlignments, GAlignmentPairs or covRleList_
I'm not sure if the problem is how I'm installing the package and that maybe I'm not using the latest version or if the commit I saw is not the definite solution.

I'm installing the package in a docker image which Dockerfile is the following:
```
# Use the latest Rocker R image
FROM r-base:latest

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libz-dev \
    liblzma-dev \
    libbz2-dev \
    libpng-dev \
    libgit2-dev \
    procps

# Install CRAN packages
RUN install2.r -e \
    BiocManager \
    optparse \
    tidyr \
    parallel \
    dplyr \
    remotes

# Install Bioconductor packages
RUN Rscript -e 'BiocManager::install(c("GenomicFeatures", "GenomicAlignments"), ask=F);'

# Install ORFik package from Bioconductor
RUN Rscript -e 'remotes::install_github("Roleren/ORFik")'
```

Thank you so much!

**Comment by Roleren** [comment]
Hey, try the newest commit, I documented it and should now work as you intended :)

**Comment by antoniasaracco** [comment]
Hi! everything is working as expected but just wanted to ask a question about how the code works. If I would downsize my bam files, lets say for example I only use certain regions of interest to filter the bam file, would the code work anyway? this would make sense? What if I only do it in bigger bam files where the function crash (bigger than 25gb)?

**Comment by Roleren** [comment]
Hello, sorry missed this message.

Do you have a 25gb bam file ?
I.e. you have not collapsed duplicate reads then ?

What I usually do is to collapse duplicate reads before alignment with ORFik::collapse.fastq(), 
then you will be able to load the whole file I believe as it will go from 25gb to ~ 0.2gb I guess

**Comment by Roleren** [comment]
Let me know how it works, will close issue on Monday if there was nothing else :)
